services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Schachbulle\BackendMenueBundle\:
    resource: '../../'
    exclude:
      - '../../BackendMenueBundle.php'
      - '../../ContaoManager/'
      - '../../Resources/'
